export const changeNameAvatar='修改昵称/头像'
export const generateTicket='生成我的观战纪念票'
export const showMoreComment='查看更多评论'
export const commentPlaceholder='说说你的想法吧~'
export const unlockCondition='解锁条件：'
export const saveSkin='保存装扮'